# Generated by Django 3.0.5 on 2020-04-20 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=5)),
                ('source', models.CharField(max_length=25)),
                ('quantity', models.FloatField(max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='material',
            name='unit',
        ),
        migrations.DeleteModel(
            name='MaterialsHistory',
        ),
        migrations.AddField(
            model_name='materialhistory',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.Material'),
        ),
    ]
